intro:
title: "Alberta Wells Dataset: Pinpointing Oil and Gas Wells from Satellite Imagery"
description:
- Pre-Print
buttons:
  Dataset: https://zenodo.org/records/13743323
  Code: https://github.com/RolnickLab/Alberta_Wells_Dataset
#  DQN Replay Dataset: https://research.google/tools/datasets/dqn-replay/
#  Blog: https://ai.googleblog.com/2020/04/an-optimistic-perspective-on-offline.html
  Paper: 'https://arxiv.org/pdf/2410.09032.pdf'
#  Code: 'https://github.com/google-research/batch_rl'  
#  Talk: 'https://slideslive.com/38928373/an-optimistic-perspective-on-offline-deep-reinforcement-learning'
#  Slides: 'https://docs.google.com/presentation/d/1ROltXr6FIeYKrnGl0tKHGWI0pL4Zo8CnvAK2-cdpQyY/edit?usp=sharing'
#   Talk (NeurIPS): 'https://slideslive.com/38922701/contributed-talk-striving-for-simplicity-in-offpolicy-deep-reinforcement-learning'
#   Poster (NeurIPS): 'pdfs/neurips_drl_poster.pdf'
#  Pytorch (Example 1): https://github.com/mila-iqia/SGI/blob/master/src/offline_dataset.py
#  Pytorch (Example 2): https://github.com/kzl/decision-transformer/tree/master/atari
  Authors: '#authors'
